/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dsa.study.problems;

import dsa.study.problems.linkedlist.DoublyLinkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DoublyLinkedList list = new DoublyLinkedList();

        // Inserting elements at the beginning
        list.insertAtBeginning(10); // List: 10
        list.printList(); // Expected Output: Doubly Linked List: 10

        list.insertAtBeginning(5); // List: 5 <-> 10
        list.printList(); // Expected Output: Doubly Linked List: 5 <-> 10

        // Inserting elements at the end
        list.insertAtEnd(15); // List: 5 <-> 10 <-> 15
        list.printList(); // Expected Output: Doubly Linked List: 5 <-> 10 <-> 15

        // Inserting elements in the middle
        list.insertAtMiddle(12, 2); // List: 5 <-> 10 <-> 12 <-> 15
        list.printList(); // Expected Output: Doubly Linked List: 5 <-> 10 <-> 12 <-> 15

        // Deleting elements from the beginning
        list.deleteAtBeginning(); // List: 10 <-> 12 <-> 15
        list.printList(); // Expected Output: Doubly Linked List: 10 <-> 12 <-> 15

        // Deleting elements from the end
        list.deleteAtEnd(); // List: 10 <-> 12
        list.printList(); // Expected Output: Doubly Linked List: 10 <-> 12

        // Deleting elements from the middle
        list.deleteAtMiddle(1); // List: 10
        list.printList(); // Expected Output: Doubly Linked List: 10
    }
}
